services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql_gym_stock_control
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: gymstock
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - gym-stock-network
  gymstock:
    image: asafeorneles/gymstock
    restart: always
    environment:
      TZ: America/Sao_Paulo
      DB_URL: jdbc:mysql://mysql:3306/gymstock
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - gym-stock-network
  redis:
    image: redis:7.2
    container_name: redis_gymstock
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gym-stock-network

networks:
  gym-stock-network:
    driver: bridge
volumes:
  redis_data:
