spring.application.name=gymstock

jwt.public.key=${JWT_PUBLIC_KEY:classpath:certs/public.key}
jwt.private.key=${JWT_PRIVATE_KEY:classpath:certs/private.key}

jwt.expiration=300
jwt.refresh-token.expiration=28800

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/gymstock}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.schemas=gymstock

spring.data.redis.port=6379
spring.data.redis.host=localhost